#pragma once

template <class T>
class CProxy_IWebRTCEvents : public IConnectionPointImpl<T, &__uuidof(_IWebRTCEvents), CComDynamicUnkArray>
{
    //Warning this class will  be regenerated by the wizard.
public:
};
